/**
 * 设计 §6：Gemini 站点专有错误码（throw / masterDispatch 映射用）。
 */
export const GEMINI_PAGE_HELPERS_MISSING = 'GEMINI_PAGE_HELPERS_MISSING';
export const GEMINI_UI_NOT_READY = 'GEMINI_UI_NOT_READY';
export const GEMINI_ASPECT_RATIO_INVALID = 'GEMINI_ASPECT_RATIO_INVALID';
export const GEMINI_INPUT_NOT_FOUND = 'GEMINI_INPUT_NOT_FOUND';
/** Step09：粘贴参考图后等待预览数量/上传指示超时 */
export const GEMINI_REF_UPLOAD_TIMEOUT = 'GEMINI_REF_UPLOAD_TIMEOUT';
export const GEMINI_SEND_FAILED = 'GEMINI_SEND_FAILED';
export const GEMINI_NOT_LOGGED_IN = 'GEMINI_NOT_LOGGED_IN';
export const GEMINI_NOT_GEMINI_TAB = 'GEMINI_NOT_GEMINI_TAB';
export const GEMINI_HOME_NAV_TIMEOUT = 'GEMINI_HOME_NAV_TIMEOUT';
export const GEMINI_IMAGE_MAIN_INJECT_FAILED = 'GEMINI_IMAGE_MAIN_INJECT_FAILED';
export const GEMINI_GENERATED_IMAGE_TIMEOUT = 'GEMINI_GENERATED_IMAGE_TIMEOUT';
export const GEMINI_FULL_IMAGE_CAPTURE_TIMEOUT = 'GEMINI_FULL_IMAGE_CAPTURE_TIMEOUT';
export const GEMINI_CLIPBOARD_FAILED = 'GEMINI_CLIPBOARD_FAILED';
/** Step13：5 分钟内无法将 Gemini 标签切回前台并获得焦点以写入剪贴板 */
export const GEMINI_CLIPBOARD_TAB_FOCUS_TIMEOUT = 'GEMINI_CLIPBOARD_TAB_FOCUS_TIMEOUT';
/** Step13：内容脚本无法使用 tabs.getCurrent 等 API 做焦点抢占 */
export const GEMINI_CLIPBOARD_TAB_FOCUS_UNAVAILABLE = 'GEMINI_CLIPBOARD_TAB_FOCUS_UNAVAILABLE';
export const GEMINI_DOWNLOAD_BUTTON_NOT_FOUND = 'GEMINI_DOWNLOAD_BUTTON_NOT_FOUND';
export const GEMINI_FETCH_CAPTURE_MISSING = 'GEMINI_FETCH_CAPTURE_MISSING';
export const GEMINI_CLIPBOARD_ARM_TIMEOUT = 'GEMINI_CLIPBOARD_ARM_TIMEOUT';
/** 仅用于 allFrames 汇总：非主 UI 的 document 立即返回，勿当作用户可见错误 */
export const GEMINI_STEP12_SKIP_FRAME = 'GEMINI_STEP12_SKIP_FRAME';
