/**
 * 设计 §6：Gemini 站点专有错误码（throw / masterDispatch 映射用）。
 */
export const GEMINI_PAGE_HELPERS_MISSING = 'GEMINI_PAGE_HELPERS_MISSING';
export const GEMINI_UI_NOT_READY = 'GEMINI_UI_NOT_READY';
export const GEMINI_ASPECT_RATIO_INVALID = 'GEMINI_ASPECT_RATIO_INVALID';
export const GEMINI_INPUT_NOT_FOUND = 'GEMINI_INPUT_NOT_FOUND';
export const GEMINI_SEND_FAILED = 'GEMINI_SEND_FAILED';
export const GEMINI_NOT_LOGGED_IN = 'GEMINI_NOT_LOGGED_IN';
export const GEMINI_NOT_GEMINI_TAB = 'GEMINI_NOT_GEMINI_TAB';
export const GEMINI_HOME_NAV_TIMEOUT = 'GEMINI_HOME_NAV_TIMEOUT';
export const GEMINI_IMAGE_MAIN_INJECT_FAILED = 'GEMINI_IMAGE_MAIN_INJECT_FAILED';
export const GEMINI_GENERATED_IMAGE_TIMEOUT = 'GEMINI_GENERATED_IMAGE_TIMEOUT';
export const GEMINI_FULL_IMAGE_CAPTURE_TIMEOUT = 'GEMINI_FULL_IMAGE_CAPTURE_TIMEOUT';
export const GEMINI_CLIPBOARD_FAILED = 'GEMINI_CLIPBOARD_FAILED';
export const GEMINI_DOWNLOAD_BUTTON_NOT_FOUND = 'GEMINI_DOWNLOAD_BUTTON_NOT_FOUND';
export const GEMINI_FETCH_CAPTURE_MISSING = 'GEMINI_FETCH_CAPTURE_MISSING';
