/**
 * 设计 §6：站点专有错误码常量（throw / masterDispatch 映射用）。
 */
export const JIMENG_PAGE_HELPERS_MISSING = 'JIMENG_PAGE_HELPERS_MISSING';
export const JIMENG_WORKBENCH_NOT_READY = 'JIMENG_WORKBENCH_NOT_READY';
export const JIMENG_PROMPT_FIELD_NOT_FOUND = 'JIMENG_PROMPT_FIELD_NOT_FOUND';
export const JIMENG_MODE_OR_PARAM_FAILED = 'JIMENG_MODE_OR_PARAM_FAILED';
export const JIMENG_PROMPT_PLACEHOLDER_MISMATCH = 'JIMENG_PROMPT_PLACEHOLDER_MISMATCH';
export const JIMENG_IMAGE_MAIN_INJECT_FAILED = 'JIMENG_IMAGE_MAIN_INJECT_FAILED';

/** step19：120s 内未出现生成中 UI */
export const JIMENG_GENERATE_START_TIMEOUT = 'JIMENG_GENERATE_START_TIMEOUT';
/** step20：自 Enter 起 600s 内未完成 */
export const JIMENG_GENERATE_WAIT_TIMEOUT = 'JIMENG_GENERATE_WAIT_TIMEOUT';
/** step20：无有效结果图 */
export const JIMENG_GENERATE_NO_OUTPUT = 'JIMENG_GENERATE_NO_OUTPUT';
/** step21：右键菜单或「复制图片」不可用 */
export const JIMENG_CONTEXT_MENU_FAILED = 'JIMENG_CONTEXT_MENU_FAILED';
/** step21：单张 15s 内未从剪贴板读到新图 */
export const JIMENG_CLIPBOARD_IMAGE_TIMEOUT = 'JIMENG_CLIPBOARD_IMAGE_TIMEOUT';
/** step22：caller Tab 缺失或 sendMessage 失败 */
export const JIMENG_RELAY_CALLER_GONE = 'JIMENG_RELAY_CALLER_GONE';
