/**
 * 设计 §6：站点专有错误码常量（throw / masterDispatch 映射用）。
 */
export const JIMENG_PAGE_HELPERS_MISSING = 'JIMENG_PAGE_HELPERS_MISSING';
export const JIMENG_WORKBENCH_NOT_READY = 'JIMENG_WORKBENCH_NOT_READY';
export const JIMENG_PROMPT_FIELD_NOT_FOUND = 'JIMENG_PROMPT_FIELD_NOT_FOUND';
export const JIMENG_MODE_OR_PARAM_FAILED = 'JIMENG_MODE_OR_PARAM_FAILED';
export const JIMENG_PROMPT_PLACEHOLDER_MISMATCH = 'JIMENG_PROMPT_PLACEHOLDER_MISMATCH';
export const JIMENG_IMAGE_MAIN_INJECT_FAILED = 'JIMENG_IMAGE_MAIN_INJECT_FAILED';
