/**
 * 即梦站点 Agent：仅本文件注册 `homeUrl`（站点前缀）/`taskBaseUrl`（本 Task 起始页）/步骤（R18）；core 不得硬编码即梦 URL（§9.1）。
 */
import { registerAgentCommands } from '../../core/registry.js';
import { JIMENG_AI_TOOL_HOME } from './jimengUrls.js';
import {
  step04_jimeng_require_logged_in,
  step05_jimeng_ensure_ai_tool_home,
  step07_jimeng_ensure_workbench_ready,
  step08_jimeng_close_open_popovers,
  step09_jimeng_ensure_mode_image_generation,
  step09_jimeng_video_ensure_mode_video_generation,
  step09b_jimeng_video_ensure_reference_mode,
  step10_jimeng_ensure_model,
  step10_jimeng_video_ensure_model,
  step11_jimeng_ensure_ratio_resolution,
  step11_jimeng_video_ensure_ratio,
  step11b_jimeng_video_ensure_duration,
  step12_jimeng_clear_form,
  step13_jimeng_paste_reference_clear_prompt,
  step14_jimeng_fill_prompt_text,
  step15_jimeng_expand_at_mentions,
  step16_jimeng_set_logged_in_marker,
  step17_jimeng_click_generate_if_needed,
  step18_jimeng_submit_prompt_enter_if_configured,
  step19_jimeng_wait_generation_started,
  step20_jimeng_wait_generation_finished,
  step21_jimeng_collect_images_via_context_menu,
  step22_jimeng_relay_images_to_caller,
} from './steps.js';

registerAgentCommands([
  {
    command: 'JIMENG_IMAGE_FILL',
    picpuckAction: 'jimengGenerateImage',
    homeUrl: 'https://jimeng.jianying.com',
    taskBaseUrl: JIMENG_AI_TOOL_HOME,
    steps: [
      step04_jimeng_require_logged_in,
      step05_jimeng_ensure_ai_tool_home,
      step07_jimeng_ensure_workbench_ready,
      step08_jimeng_close_open_popovers,
      step09_jimeng_ensure_mode_image_generation,
      step10_jimeng_ensure_model,
      step11_jimeng_ensure_ratio_resolution,
      step12_jimeng_clear_form,
      step13_jimeng_paste_reference_clear_prompt,
      step14_jimeng_fill_prompt_text,
      step15_jimeng_expand_at_mentions,
      step16_jimeng_set_logged_in_marker,
      step17_jimeng_click_generate_if_needed,
      step18_jimeng_submit_prompt_enter_if_configured,
      step19_jimeng_wait_generation_started,
      step20_jimeng_wait_generation_finished,
      step21_jimeng_collect_images_via_context_menu,
      step22_jimeng_relay_images_to_caller,
    ],
  },
  {
    command: 'JIMENG_VIDEO_FILL',
    picpuckAction: 'jimengGenerateVideo',
    homeUrl: 'https://jimeng.jianying.com',
    taskBaseUrl: JIMENG_AI_TOOL_HOME,
    steps: [
      step04_jimeng_require_logged_in,
      step05_jimeng_ensure_ai_tool_home,
      step07_jimeng_ensure_workbench_ready,
      step08_jimeng_close_open_popovers,
      step09_jimeng_video_ensure_mode_video_generation,
      step09b_jimeng_video_ensure_reference_mode,
      step10_jimeng_video_ensure_model,
      step11_jimeng_video_ensure_ratio,
      step11b_jimeng_video_ensure_duration,
      step12_jimeng_clear_form,
      step13_jimeng_paste_reference_clear_prompt,
      step14_jimeng_fill_prompt_text,
      step15_jimeng_expand_at_mentions,
    ],
  },
]);
