export const DOUBAO_NOT_LOGGED_IN = 'DOUBAO_NOT_LOGGED_IN';
export const DOUBAO_MAIN_INJECT_FAILED = 'DOUBAO_MAIN_INJECT_FAILED';
export const DOUBAO_SKILL_NOT_FOUND = 'DOUBAO_SKILL_NOT_FOUND';
export const DOUBAO_RATIO_MENU_FAILED = 'DOUBAO_RATIO_MENU_FAILED';
export const DOUBAO_EDITOR_NOT_FOUND = 'DOUBAO_EDITOR_NOT_FOUND';
export const DOUBAO_WORKBENCH_NOT_READY = 'DOUBAO_WORKBENCH_NOT_READY';
